#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
template_root="$(cd "${script_dir}/../assets/templates" && pwd)"
manifest_path="hermes/.hermes-runtime-manifest"
begin_marker="BEGIN HERMES RUNTIME MANAGED BLOCK"
end_marker="END HERMES RUNTIME MANAGED BLOCK"

usage() {
  cat <<'EOF'
Usage:
  hermes-project.sh install [--agents codex,claude,cursor] [--init-memory] [--project-name "Name"]
  hermes-project.sh uninstall [--agents codex,claude,cursor] [--remove-memory | --purge-memory]

Installs or removes Hermes Runtime project integration.

Options:
  --agents        Comma-separated agent targets. Defaults to codex.
  --init-memory   Create a project-local hermes/ memory skeleton.
  --project-name  Project name used when initializing hermes/memory/core/project.md.
  --remove-memory Remove files created by Hermes Runtime according to its manifest.
  --purge-memory  Remove the entire hermes/ directory.
EOF
}

command="${1:-}"
if [ -z "$command" ] || [ "$command" = "--help" ] || [ "$command" = "-h" ]; then
  usage
  exit 0
fi
shift

agents="codex"
init_memory=0
remove_memory=0
purge_memory=0
project_name="$(basename "$PWD")"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --agents)
      agents="${2:-}"
      [ -n "$agents" ] || { echo "--agents requires a value" >&2; exit 1; }
      shift 2
      ;;
    --init-memory)
      init_memory=1
      shift
      ;;
    --project-name)
      project_name="${2:-}"
      [ -n "$project_name" ] || { echo "--project-name requires a value" >&2; exit 1; }
      shift 2
      ;;
    --remove-memory)
      remove_memory=1
      shift
      ;;
    --purge-memory)
      purge_memory=1
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

ensure_manifest() {
  local created_root=0
  if [ ! -d hermes ]; then
    mkdir -p hermes
    created_root=1
  fi
  if [ ! -e "$manifest_path" ]; then
    {
      echo "# Hermes Runtime manifest v1"
      echo "# Generated by skills/hermes-runtime/scripts/hermes-project.sh"
    } >"$manifest_path"
    if [ "$created_root" -eq 1 ]; then
      echo "memory-root hermes" >>"$manifest_path"
    fi
  fi
}

record_manifest() {
  local kind="$1"
  local path="$2"
  ensure_manifest
  grep -Fxq "$kind $path" "$manifest_path" || echo "$kind $path" >>"$manifest_path"
}

manifest_has() {
  local kind="$1"
  local path="$2"
  [ -f "$manifest_path" ] && grep -Fxq "$kind $path" "$manifest_path"
}

cleanup_empty_parents() {
  local path="$1"
  local dir
  dir="$(dirname "$path")"
  while [ "$dir" != "." ] && [ "$dir" != "/" ]; do
    rmdir "$dir" 2>/dev/null || break
    dir="$(dirname "$dir")"
  done
}

remove_managed_block() {
  local path="$1"
  [ -e "$path" ] || return 0

  local tmp
  tmp="$(mktemp)"
  awk -v begin="$begin_marker" -v end="$end_marker" '
    index($0, begin) { skip = 1; next }
    index($0, end) { skip = 0; next }
    !skip { print }
  ' "$path" >"$tmp"

  if grep -Eq '[^[:space:]]' "$tmp"; then
    mv "$tmp" "$path"
  else
    rm -f "$tmp" "$path"
    cleanup_empty_parents "$path"
  fi
}

hermes_rule_body() {
  cat <<'EOF'
<!-- BEGIN HERMES RUNTIME MANAGED BLOCK -->
# Hermes Runtime Project Memory

Before meaningful engineering work:

1. Read `hermes/retrieval/index.md` if it exists.
2. Load only the Hermes memory files relevant to the task.
3. Create or update a task record under `hermes/tickets/`.

Before claiming completion:

1. Record context, goal, changed files, behavior changes, verification, and follow-ups in the task record.
2. Update bug, feature, decision, workflow, or current-state memory when the task creates durable context.
3. State any verification that could not be run.

Do not use legacy `docs/` as the Hermes memory root. Hermes memory belongs under `hermes/`.
<!-- END HERMES RUNTIME MANAGED BLOCK -->
EOF
}

cursor_rule_file() {
  cat <<'EOF'
---
description: Enforce Hermes Runtime project memory
globs:
alwaysApply: true
---
EOF
  hermes_rule_body
}

write_agent_file() {
  local path="$1"
  local mode="$2"

  mkdir -p "$(dirname "$path")"
  if [ -e "$path" ]; then
    remove_managed_block "$path"
    {
      echo
      hermes_rule_body
    } >>"$path"
    record_manifest agent-block "$path"
  else
    if [ "$mode" = "cursor" ]; then
      cursor_rule_file >"$path"
    else
      hermes_rule_body >"$path"
    fi
    record_manifest agent-file "$path"
  fi
}

install_agents() {
  local agent
  local old_ifs="$IFS"
  IFS=','
  for agent in $agents; do
    agent="$(printf "%s" "$agent" | tr -d '[:space:]')"
    case "$agent" in
      codex)
        write_agent_file "AGENTS.md" "markdown"
        ;;
      claude)
        write_agent_file "CLAUDE.md" "markdown"
        ;;
      cursor)
        write_agent_file ".cursor/rules/hermes-memory.mdc" "cursor"
        ;;
      "")
        ;;
      *)
        echo "Unknown agent target: $agent" >&2
        exit 1
        ;;
    esac
  done
  IFS="$old_ifs"
}

uninstall_agents() {
  local agent
  local path
  local old_ifs="$IFS"
  IFS=','
  for agent in $agents; do
    agent="$(printf "%s" "$agent" | tr -d '[:space:]')"
    case "$agent" in
      codex) path="AGENTS.md" ;;
      claude) path="CLAUDE.md" ;;
      cursor) path=".cursor/rules/hermes-memory.mdc" ;;
      "") continue ;;
      *)
        echo "Unknown agent target: $agent" >&2
        exit 1
        ;;
    esac

    if manifest_has agent-file "$path"; then
      rm -f "$path"
      cleanup_empty_parents "$path"
    else
      remove_managed_block "$path"
    fi
  done
  IFS="$old_ifs"
}

create_dir() {
  local path="$1"
  if [ ! -d "$path" ]; then
    mkdir -p "$path"
    record_manifest memory-dir "$path"
  fi
}

copy_template() {
  local source="$1"
  local target="$2"
  local mode="${3:-file}"

  create_dir "$(dirname "$target")"
  if [ -e "$target" ]; then
    return 0
  fi

  cp "${template_root}/${source}" "$target"
  if [ "$target" = "hermes/memory/core/project.md" ]; then
    HERMES_PROJECT_NAME="$project_name" perl -0pi -e 's/<project-name>/$ENV{HERMES_PROJECT_NAME}/g' "$target"
  fi
  if [ "$mode" = "executable" ]; then
    chmod +x "$target"
  fi
  record_manifest memory-file "$target"
}

init_hermes_memory() {
  ensure_manifest

  copy_template "retrieval/index.md" "hermes/retrieval/index.md"
  copy_template "retrieval/routing-rules.md" "hermes/retrieval/routing-rules.md"

  copy_template "runtime/README.md" "hermes/runtime/README.md"
  copy_template "runtime/context-loading.md" "hermes/runtime/context-loading.md"
  copy_template "runtime/task-lifecycle.md" "hermes/runtime/task-lifecycle.md"
  copy_template "runtime/context-budget.yaml" "hermes/runtime/context-budget.yaml"

  copy_template "memory/core/project.md" "hermes/memory/core/project.md"
  copy_template "memory/core/current-state.md" "hermes/memory/core/current-state.md"
  copy_template "memory/core/architecture.md" "hermes/memory/core/architecture.md"
  copy_template "memory/core/constraints.md" "hermes/memory/core/constraints.md"
  copy_template "memory/core/glossary.md" "hermes/memory/core/glossary.md"

  copy_template "memory/conventions/ai-rules.md" "hermes/memory/conventions/ai-rules.md"
  copy_template "memory/conventions/naming.md" "hermes/memory/conventions/naming.md"
  copy_template "memory/conventions/error-handling.md" "hermes/memory/conventions/error-handling.md"
  copy_template "memory/conventions/logging.md" "hermes/memory/conventions/logging.md"

  copy_template "memory/workflows/development.md" "hermes/memory/workflows/development.md"
  copy_template "memory/workflows/debugging.md" "hermes/memory/workflows/debugging.md"
  copy_template "memory/workflows/testing.md" "hermes/memory/workflows/testing.md"
  copy_template "memory/workflows/release.md" "hermes/memory/workflows/release.md"

  copy_template "tickets/TEMPLATE.md" "hermes/tickets/TEMPLATE.md"
  copy_template "memory/bugs/TEMPLATE.md" "hermes/memory/bugs/TEMPLATE.md"
  copy_template "memory/features/TEMPLATE.md" "hermes/memory/features/TEMPLATE.md"
  copy_template "memory/decisions/ADR-TEMPLATE.md" "hermes/memory/decisions/ADR-TEMPLATE.md"

  copy_template "scripts/new-ticket.sh" "hermes/scripts/new-ticket.sh" "executable"
  copy_template "scripts/new-bug.sh" "hermes/scripts/new-bug.sh" "executable"
  copy_template "scripts/new-feature.sh" "hermes/scripts/new-feature.sh" "executable"
  copy_template "scripts/new-adr.sh" "hermes/scripts/new-adr.sh" "executable"
  copy_template "scripts/check-doc-sync.sh" "hermes/scripts/check-doc-sync.sh" "executable"
}

remove_manifest_memory() {
  [ -f "$manifest_path" ] || return 0

  if grep -Fxq "memory-root hermes" "$manifest_path"; then
    rm -rf hermes
    return 0
  fi

  awk '$1 == "memory-file" { print substr($0, index($0,$2)) }' "$manifest_path" | while IFS= read -r path; do
    rm -f "$path"
  done

  awk '$1 == "memory-dir" { print substr($0, index($0,$2)) }' "$manifest_path" | sort -r | while IFS= read -r path; do
    rmdir "$path" 2>/dev/null || true
  done

  rm -f "$manifest_path"
  if [ -d hermes ]; then
    find hermes -depth -type d 2>/dev/null | while IFS= read -r dir; do
      rmdir "$dir" 2>/dev/null || true
    done
  fi
}

case "$command" in
  install)
    install_agents
    if [ "$init_memory" -eq 1 ]; then
      init_hermes_memory
    fi
    echo "Hermes Runtime install complete."
    ;;
  uninstall)
    uninstall_agents
    if [ "$purge_memory" -eq 1 ]; then
      rm -rf hermes
    elif [ "$remove_memory" -eq 1 ]; then
      remove_manifest_memory
    fi
    echo "Hermes Runtime uninstall complete."
    ;;
  *)
    echo "Unknown command: $command" >&2
    usage >&2
    exit 1
    ;;
esac
